services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - arquitecturacloud057-network
networks:
  arquitecturacloud057-network:
    driver: bridge